# config.yml

backend:
  name: git-gateway
  branch: master
media_folder: "assets/uploads"
collections:
  - name: "Experience"
    label: "Experience"
    folder: "_experience/"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "author" }
      - { label: "Date", name: "rank", widget: "datetime" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "Extracurriculars"
    label: "Extracurriculars"
    folder: "_extracurriculars/"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "author" }
      - { label: "Date", name: "rank", widget: "datetime" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "Awards"
    label: "Awards"
    folder: "_awards/"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "author" }
      - { label: "Date", name: "rank", widget: "datetime" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "News"
    label: "News"
    folder: "_news/"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "author" }
      - { label: "Date", name: "rank", widget: "datetime" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "URL", name: "url", widget: "string" }
